name: Build Lawnicons & Pissel Overlay
on: 
  push:
  workflow_dispatch:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install telethon

      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execution permission to Gradle Wrapper
        run:  chmod +x gradlew

      - name: Build debug APK
        run: |
          echo Building Lawnicons 
          ./gradlew assembleDebug
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Debug APK
          path: |
            app/build/outputs/apk/debug/app-debug.apk

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: workflow.yml
          run_number: ${{ github.run_number-1 }}
          name: ThemedIconsOverlay
          path: build/

      - name: Build Pissel Overlay
        run:  .github/scripts/build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ThemedIconsOverlay
          path: |
            build/ThemedIconsOverlay.apk
      - name: Send to Telegram
        env:
          APIID: ${{ secrets.APIID }}
          APIHASH: ${{ secrets.APIHASH }}
          BOTTOKEN: ${{ secrets.BOTTOKEN }}
          CHATID: ${{ secrets.CHATID }}
        run: python3 .github/scripts/send.py build/ThemedIconsOverlay.apk  ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}